name: ppera-env
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # === Core Python ===
  - python=3.9
  - pip

  # === Core Data Science Stack ===
  - numpy>=1.21
  - pandas>=1.3
  - scipy>=1.7
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  - joblib

  # === Machine Learning & Deep Learning ===
  - pytorch>=1.12
  - torchvision
  - torchaudio
  - cpuonly  # Remove this line if you need GPU support

  # === Development & Code Quality ===
  - ruff
  - jupyter
  - jupyterlab
  - ipykernel
  - tqdm

  # === System & Build Tools ===
  - setuptools
  - wheel

  # === Pip-only Dependencies ===
  - pip:
    # === Recommendation Systems ===
    - recommenders>=1.2.0
    - cornac>=2.0
    - scikit-surprise>=1.1

    # === Experiment Tracking & MLOps ===
    - mlflow>=2.0
    - tensorboard

    # === Data Processing & Validation ===
    - category-encoders>=2.5
    - pandera>=0.15
    - easydict>=1.10

    # === Web Framework & API ===
    - fastapi>=0.100
    - uvicorn[standard]
    - gunicorn

    # === Optimization & Hyperparameter Tuning ===
    - optuna>=3.0
    - hyperopt>=0.2

    # === Utilities ===
    - pyyaml>=6.0
    - requests>=2.28
    - python-slugify>=8.0

    # === Testing & Quality ===
    - pytest>=7.0
    - hypothesis>=6.0

    # === NLP & Text Processing (if needed) ===
    - nltk>=3.8
    - transformers>=4.20
    - tokenizers>=0.13

    # === Additional ML Tools ===
    - lightgbm>=4.0
    - statsmodels>=0.14
    - networkx>=3.0
    - numba>=0.58

    # === Performance & Monitoring ===
    - memory-profiler>=0.60
    - psutil>=5.9

    # === Local Package ===
    - -e .  # Install ppera package in development mode
