name: qpera-env
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # === Core Python ===
  - python=3.9.*
  - pip=23.*

  # === Core Data Science Stack (conda-optimized) ===
  - numpy>=1.21
  - pandas>=1.3
  - scipy>=1.7
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  - joblib

  # === System & Build Tools ===
  - setuptools
  - wheel

  # === Basic utilities available via conda ===
  - tqdm
  - jupyter
  - jupyterlab
  - ipykernel

  # === Everything else via pip ===
  - pip:
    # Project itself will be installed by Makefile
    # Dev tools will be installed by Makefile when needed
    # PyTorch will be installed by Makefile with correct index
    - requests>=2.28
    - pyyaml>=6.0
