[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "personalization_privacy_and_explainability_of_recommendation_algorithms"
version = "0.0.1"
description = "The aim of the project is to analyse in depth the four main families of recommendation algorithms (collaborative filtering, content-based, learning2rank, reinforcement learning) in terms of their resilience to the data burden, their resistance to anonymisation, the ability of the algorithms to generate explanations, and the ethical risks associated with the implementation of a given algorithm. The last point is related to the AI Act recently adopted by the European Union and the introduction of a taxonomy of ethical risks, as well as the Omnibus Directive. The project plans to select different recommendation scenarios (datasets and application areas), implement metrics to assess the robustness of algorithms, and conduct extensive experiments investigating the behaviour of different algorithm families in the space of evaluated criteria."
authors = [
  { name = "Julia Podsadna \u0026 Bartosz Chwi\u0142kowski" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.13.0"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.ruff.lint.isort]
known_first_party = ["personalization_privacy_and_explainability_of_recommendation_algorithms"]
force_sort_within_sections = true
